<?php

namespace AppBundle\Repository;

/**
 * UserTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
